apiVersion: policies.kreepy.kubecrew.de/v1alpha1
kind: CRDCleanupPolicy
metadata:
  labels:
    app.kubernetes.io/name: kreepy
    app.kubernetes.io/managed-by: kustomize
  name: crdcleanuppolicy-sample
spec:
  crdsversions:
    - name: samples.example.com
